<?php
if(isset($_POST['keys'])){
	$pum=trim($_POST['keys']);
	$kampung=trim($_POST['kampung']);
	$kecamatan=trim($_POST['kecamatan']);
	$kabupaten=trim($_POST['kabupaten']);
	$provinsi=trim($_POST['provinsi']);
	$tahun=trim($_POST['tahun']);
	$hukum=trim($_POST['hukum']);
	$peta=trim($_POST['peta']);
	$lat=trim($_POST['lat']);
	$lon=trim($_POST['lon']);
	$selatan=trim($_POST['selatan']);
	$utara=trim($_POST['utara']);
	$timur=trim($_POST['timur']);
	$barat=trim($_POST['barat']);
}

?>